### ISSUE TITLE
record to bag   issues 

### ISSUE THREAD

**Issue by qimiao-hub** [daohu527/bag_convert#3]
Failed to load Python extension for LZ4 support. LZ4 compression will not be available.

drwxrwxr-x  2 zhiqiangcui zhiqiangcui      4096 11月 12 20:22 ./
drwxr-xr-x 38 zhiqiangcui zhiqiangcui      4096 11月 12 19:51 ../
-rw-r--r--  1 zhiqiangcui zhiqiangcui 262835234 11月 12 20:16 20241112171350.record
-rw-rw-r--  1 zhiqiangcui zhiqiangcui      4117 11月 12 20:30 demo.bag

**Comment by daohu527** [comment]
could you pls install lz4
```
pip install lz4
```
